# Generated by Django 3.0.7 on 2020-06-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(height_field=64, upload_to='uploads/', width_field=64)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('room_number', models.CharField(max_length=16)),
                ('subjects_taught', models.CharField(default='', max_length=512)),
            ],
        ),
    ]
